prometheus:
  # -- Volume of storage requested for each Prometheus PVC, in Gi
  volume_claim_storage_request: "50"
  kube_controller_manager: false
  kube_scheduler: false
  kube_proxy: false
  kube_api_server: true
  kubelet: true
  service_monitor: false
  kube_state_metric: true
  node_exporter: true
  alertmanager_log_level: info
  retentionSize: "10GB"
  retention: 1d

glueops_node_and_tolerations:
  nodeSelector:
    glueops.dev/role: "glueops-platform"
  tolerations:
    - key: "glueops.dev/role"
      operator: "Equal"
      value: "glueops-platform"
      effect: "NoSchedule"

host_network:
  enabled: true
  external_secrets:
    webhook_port: 45010
  cert_manager:
    webhook_secure_port: 45020
  nginx_public:
    controller:
      host_port:
        ports:
          http: 45030
          https: 45031
  kube_pometheus_stack:
    prometheusOperator:
      tls:
        internal_port: 45040
      admissionWebhooks:
        deployment:
          tls:
            internal_port: 45041

captain_domain: nonprod.gliese667cc.onglueops

thanos:
  storage:
    type: s3
    config:
        bucket: nonprodgliese667cconglueopsrocks-eca3-thanos
        endpoint: fsn1.your-objectstorage.com
        access_key: JYAXBKO07A3I9WK1TXHJ
        secret_key: O1ZAocvfDLoYWlkVoD1Fnc2ipAjO73ZTWyCygmLv

loki:
  storage:
   bucketNames:
        chunks: nonprodgliese667cconglueopsrocks-eca3-loki
        ruler: nonprodgliese667cconglueopsrocks-eca3-loki
        admin: nonprodgliese667cconglueopsrocks-eca3-loki
   type: s3
   s3:
      s3: nonprodgliese667cconglueopsrocks-eca3-loki
      endpoint: https://fsn1.your-objectstorage.com
      region: us-east-1
      secretAccessKey: O1ZAocvfDLoYWlkVoD1Fnc2ipAjO73ZTWyCygmLv
      accessKeyId: JYAXBKO07A3I9WK1TXHJ
      s3ForcePathStyle: false
      insecure: false
   