prometheus:
  # -- Volume of storage requested for each Prometheus PVC, in Gi
  volume_claim_storage_request: "50"
  kube_controller_manager: false
  kube_scheduler: false
  kube_proxy: false
  kube_api_server: true
  kubelet: true
  service_monitor: false
  kube_state_metric: true
  node_exporter: true
  alertmanager_log_level: info
  retentionSize: "10GB"
  retention: 1d

glueops_node_and_tolerations:
  nodeSelector:
    glueops.dev/role: "glueops-platform"
  tolerations:
    - key: "glueops.dev/role"
      operator: "Equal"
      value: "glueops-platform"
      effect: "NoSchedule"

host_network:
  enabled: true
  external_secrets:
    webhook_port: 45010
  cert_manager:
    webhook_secure_port: 45020
  nginx_public:
    controller:
      host_port:
        ports:
          http: 45030
          https: 45031
  kube_pometheus_stack:
    prometheusOperator:
      tls:
        internal_port: 45040
      admissionWebhooks:
        deployment:
          tls:
            internal_port: 45041

captain_domain: nonprod.gliese667cc.onglueops

thanos:
  storage:
    type: s3
    config:
        bucket: nonprodgliese667cconglueopsrocks-eca3-thanos
        endpoint: fsn1.your-objectstorage.com
        access_key: JYAXBKO07A3I9WK1TXHJ
        secret_key: O1ZAocvfDLoYWlkVoD1Fnc2ipAjO73ZTWyCygmLv

loki:
  storage:
   bucketNames:
        chunks: nonprodgliese667cconglueopsrocks-eca3-loki
        ruler: nonprodgliese667cconglueopsrocks-eca3-loki
        admin: nonprodgliese667cconglueopsrocks-eca3-loki
   type: s3
   s3:
      s3: nonprodgliese667cconglueopsrocks-eca3-loki
      endpoint: https://fsn1.your-objectstorage.com
      region: us-east-1
      secretAccessKey: O1ZAocvfDLoYWlkVoD1Fnc2ipAjO73ZTWyCygmLv
      accessKeyId: JYAXBKO07A3I9WK1TXHJ
      s3ForcePathStyle: false
      insecure: false
  chunkConfig:
    replicas: 2
    maxItemMemory: 2
    allocatedMemory: 2024
    batchSize: 2
    parallelism: 2
    writebackParallelism: 1
    writebackBuffer: 1000
    writebackSizeLimit: 500MB 

otel:
  replicas: 1
  name_override: "glueops-otel"
  config:
  
  manager:
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
      tag: ""
    collectorImage:
      repository: "otel/opentelemetry-collector-contrib"
      tag: 0.123.0
    opampBridgeImage:
      repository: ""
      tag: ""
    targetAllocatorImage:
      repository: ""
      tag: ""
    autoInstrumentationImage:
      java:
        repository: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java"
        tag: "2.7.0"
      nodejs:
        repository: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs"
        tag: "0.52.1"
      python:
        repository: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python"
        tag: "0.47b0"
      dotnet:
        repository: ""
        tag: ""
      apacheHttpd:
        repository: ""
        tag: ""
      # The Go instrumentation support in the operator is disabled by default.
      # To enable it, use the operator.autoinstrumentation.go feature gate.
      go:
        repository: ""
        tag: ""
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi    

tempo:
  storage:
    placeholder_tempo_storage: {}
  remote_url: ["http://localhost:9090/api/v1/write"]

  compaction_block_retention: "168h"